return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 20,
  height = 10,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 5,
  nextobjectid = 70,
  properties = {},
  tilesets = {
    {
      name = "test",
      firstgid = 1,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 15,
      image = "../../../world.png",
      imagewidth = 480,
      imageheight = 480,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 225,
      tiles = {}
    },
    {
      name = "Objects",
      firstgid = 226,
      class = "",
      tilewidth = 96,
      tileheight = 96,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 2,
      tiles = {
        {
          id = 1,
          image = "../../../reactor/reactor-Sheet.png",
          width = 96,
          height = 96
        },
        {
          id = 2,
          image = "../../../objects/tree.png",
          width = 48,
          height = 96
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 20,
      height = 10,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 121, 124, 122, 124, 122, 124, 122, 124, 124, 124, 122, 124, 122, 125, 0, 0, 0,
        0, 0, 0, 136, 137, 138, 139, 137, 137, 137, 138, 137, 138, 139, 139, 139, 140, 0, 0, 0,
        0, 0, 0, 136, 137, 138, 139, 137, 138, 137, 138, 137, 137, 137, 138, 139, 140, 0, 0, 0,
        0, 0, 0, 136, 137, 138, 139, 137, 138, 137, 138, 137, 138, 137, 138, 139, 140, 0, 0, 0,
        0, 0, 0, 136, 137, 138, 139, 137, 138, 137, 137, 138, 137, 138, 139, 139, 140, 0, 0, 0,
        0, 0, 0, 136, 137, 137, 137, 137, 138, 139, 137, 137, 137, 137, 138, 139, 140, 0, 0, 0,
        0, 0, 0, 151, 152, 152, 152, 152, 152, 152, 152, 152, 152, 152, 152, 154, 155, 0, 0, 0,
        0, 0, 0, 166, 167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 169, 170, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "Objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 510,
          y = 211,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 273.333,
          y = 136,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 357.333,
          y = 142.333,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 396.333,
          y = 211.333,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 446.667,
          y = 240.333,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 412,
          y = 166,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 404,
          y = 62.6667,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 499.333,
          y = 107.667,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 471.5,
          y = 139.5,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 76,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 159.5,
          y = 153.5,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 226.333,
          y = 221,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 112.666,
          y = 221.333,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 163,
          y = 250.333,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 128.333,
          y = 176,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 120.333,
          y = 72.667,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 215.666,
          y = 117.667,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 187.833,
          y = 149.5,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 164.333,
          y = 86,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 369.833,
          y = 218,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 256.166,
          y = 218.333,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 306.5,
          y = 247.333,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 271.833,
          y = 173,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 263.833,
          y = 69.667,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 359.166,
          y = 114.667,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 331.333,
          y = 146.5,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "Tree",
          type = "",
          shape = "rectangle",
          x = 307.833,
          y = 83,
          width = 48,
          height = 96,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "Area",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 69,
          name = "MobSpawn",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 96,
          width = 287.23,
          height = 97.5,
          rotation = 0,
          visible = true,
          properties = {
            ["amount"] = 2
          }
        }
      }
    }
  }
}
